apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: argo-workflows-ui-user-admin
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: argo-workflows-ui-user-admin
subjects:
  - kind: ServiceAccount
    name: argo-workflows-ui-user-admin
    namespace: argo-workflows
